--
-- Title: 과일로 만든 아이스크림 고르기 
-- Date: 23.05.07
--  

SELECT FLAVOR FROM ICECREAM_INFO
WHERE FLAVOR IN (SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 ORDER BY TOTAL_ORDER)
AND INGREDIENT_TYPE = 'fruit_based';