--
-- Title: 서울에 위치한 식당 목록 출력하기 
-- Date: 23.05.09
--
SELECT REST_ID, REST_NAME,FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REST_SCORE),2) AS SCORE
FROM REST_INFO AS A INNER JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, B.FAVORITES ASC