--
-- Title: 서울에 위치한 식당 목록 출력하기 
-- Date: 23.05.09
--
SELECT A.REST_ID, REST_NAME,FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A INNER JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
GROUP BY B.REST_ID
HAVING A.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, A.FAVORITES DESC