--
-- Title: 오프라인/온라인 판매 데이터 통합하기 
-- Date: 23.05.09
--
(SELECT DATE_FORMAT(SALES_DATE,"%y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT  
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE,"%y-%m-%d") as SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC